export const BASELINE_OPERATION_TYPES = [
	"foundation.baseline",
	"catalog.distributor.archive",
	"catalog.distributor.create",
	"catalog.distributor.update",
	"catalog.packaging_type.archive",
	"catalog.packaging_type.create",
	"catalog.packaging_type.update",
	"catalog.product_template.archive",
	"catalog.product_template.create",
	"catalog.product_template.update",
	"catalog.raw_material_type.archive",
	"catalog.raw_material_type.create",
	"catalog.raw_material_type.update",
	"client.create",
	"client.update",
	"courier.sale.cancel",
	"courier.sale.create",
	"courier.stock.load.create",
	"courier.unload.create",
	"distributor.cash.withdraw",
	"distributor.discount.assign",
	"distributor.sale.cancel",
	"distributor.sale.create",
	"distributor.stock.correct",
	"direct_accounting.sale.create",
	"direct_accounting.sale.delete",
	"direct_accounting.sale.update",
	"direct_accounting.receipt.create",
	"direct_accounting.receipt.delete",
	"direct_accounting.receipt.update",
	"direct_accounting.expense.create",
	"direct_accounting.expense.delete",
	"direct_accounting.expense.update",
	"direct_accounting.transfer.create",
	"direct_accounting.transfer.delete",
	"direct_accounting.transfer.update",
	"production.notification.complete",
	"production.notification.create",
	"production.packaging_intake.create",
	"production.product_batch.create",
	"production.product_transfer.create",
	"production.raw_material_intake.create",
	"production.raw_material.correct",
	"user.create",
	"user.identity.update",
	"user.password.change",
	"user.role.update",
	"user.password.reset",
] as const;

export type BaselineOperationType = (typeof BASELINE_OPERATION_TYPES)[number];

export const OPERATION_STATUS = {
	succeeded: "succeeded",
	failed: "failed",
} as const;

export type OperationStatus = (typeof OPERATION_STATUS)[keyof typeof OPERATION_STATUS];
